services:
    postgres:
      image: postgres:15
      ports:
        - "5432:5432"
      environment:
        POSTGRES_DB: pdm-agent
        POSTGRES_USER: pdm-user
        POSTGRES_PASSWORD: password
      volumes:
        - postgres_data:/var/lib/postgresql/data

    redis:
      image: redis:alpine
      ports:
        - "6379:6379"

volumes:
  postgres_data: